# This file is part of James CI.
#
# James CI is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# James CI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with James CI. If not, see <http://www.gnu.org/licenses/>.
#
#
# Copyright (C)
#   2017 Alexander Haase <ahaase@alexhaase.de>
#

# The following path will be used as main storage for all of the CI's data.
# Configurations of each pipeline, the job's log-files and similar data will be
# stored here.
root: /srv/james/data

# If the default scheduler 'james-schedule' doesn't fit your needs, you may
# define a custom one. It takes two arguments: The project's name and the ID of
# the pipeline to be scheduled.
# scheduler: /path/to/scheduler

runner:
  # If the runner should be run inside a vm or container, you'll need a wrapper
  # to setup the runner's environement and executing the runner in it. It takes
  # three arguments: The project's name, the ID of the pipeline and the job's
  # name.
  # wrapper: /path/to/wrapper

  # The hostname should be printed before the job starts, or some dependencies
  # should be installed? No problem! Just define a bunch of script to be
  # executed before the job.
  #
  # Note: These commands will be evaluated by a shell, i.e. you may use
  #       arguments, pipes, etc.
  # prolog_script:
  # - echo 'running on' $(hostname)
  # - apt-get update && apt-get upgrade

  # Define a template for the git clone URL, used by the runner to clone the
  # pipeline's repository. Use '{}' as placeholder for the project's name.
  git_url: 'file:///srv/git/{}.git'
